import { WordCategory } from './types';

export const BUILTIN_CATEGORIES: WordCategory[] = [
  {
    id: 'animals',
    name: 'Animals',
    description: 'Learn names of common and cute animals',
    icon: 'dog',
    words: [
      { word: 'Cat', translation: 'Feline helper', translationRu: 'Кошка' },
      { word: 'Dog', translation: 'Barking friend', translationRu: 'Собака' },
      { word: 'Rabbit', translation: 'Long-eared hopper', translationRu: 'Кролик' },
      { word: 'Lion', translation: 'King of the jungle', translationRu: 'Лев' },
      { word: 'Panda', translation: 'Bamboo eater', translationRu: 'Панда' },
      { word: 'Monkey', translation: 'Climbing acrobat', translationRu: 'Обезьяна' },
      { word: 'Tiger', translation: 'Striped hunter', translationRu: 'Тигр' },
      { word: 'Horse', translation: 'Fast runner', translationRu: 'Лошадь' },
      { word: 'Bear', translation: 'Forest giant', translationRu: 'Медведь' },
      { word: 'Elephant', translation: 'Trunk nose', translationRu: 'Слон' },
      { word: 'Fox', translation: 'Clever friend', translationRu: 'Лиса' },
      { word: 'Frog', translation: 'Green hopper', translationRu: 'Лягушка' },
      { word: 'Giraffe', translation: 'Long neck', translationRu: 'Жираф' },
      { word: 'Zebra', translation: 'Striped horse', translationRu: 'Зебра' },
      { word: 'Penguin', translation: 'Ice bird', translationRu: 'Пингвин' },
      { word: 'Koala', translation: 'Eucalyptus climber', translationRu: 'Коала' },
      { word: 'Kangaroo', translation: 'Pouch jumper', translationRu: 'Кенгуру' },
      { word: 'Dolphin', translation: 'Ocean swimmer', translationRu: 'Дельфин' },
      { word: 'Whale', translation: 'Huge sea friend', translationRu: 'Кит' },
      { word: 'Wolf', translation: 'Forest hunter', translationRu: 'Волк' },
      { word: 'Owl', translation: 'Wise night bird', translationRu: 'Сова' },
      { word: 'Cow', translation: 'Milk helper', translationRu: 'Корова' },
      { word: 'Sheep', translation: 'Wool friend', translationRu: 'Овца' },
      { word: 'Deer', translation: 'Horned friend', translationRu: 'Олень' },
      { word: 'Squirrel', translation: 'Nut collector', translationRu: 'Белка' },
      { word: 'Hedgehog', translation: 'Spiky friend', translationRu: 'Ёж' },
      { word: 'Mouse', translation: 'Tiny helper', translationRu: 'Мышь' },
      { word: 'Pig', translation: 'Pink snout', translationRu: 'Свинья' },
      { word: 'Duck', translation: 'Water waddler', translationRu: 'Утка' },
      { word: 'Goat', translation: 'Horned helper', translationRu: 'Коза' },
    ],
  },
  {
    id: 'fruits',
    name: 'Fruits',
    description: 'Juicy and delicious sweet treats',
    icon: 'apple',
    words: [
      { word: 'Apple', translation: 'Crisp fruit', translationRu: 'Яблоко' },
      { word: 'Banana', translation: 'Yellow sweet strip', translationRu: 'Банан' },
      { word: 'Lemon', translation: 'Sour yellow', translationRu: 'Лимон' },
      { word: 'Peach', translation: 'Soft pink sweet', translationRu: 'Персик' },
      { word: 'Cherry', translation: 'Red twins', translationRu: 'Вишня' },
      { word: 'Orange', translation: 'Juicy dynamic color', translationRu: 'Апельсин' },
      { word: 'Melon', translation: 'Big sweet fruit', translationRu: 'Дыня' },
      { word: 'Grape', translation: 'Vine clusters', translationRu: 'Виноград' },
      { word: 'Pear', translation: 'Sweet teardrop', translationRu: 'Груша' },
      { word: 'Plum', translation: 'Purple sweet', translationRu: 'Слива' },
      { word: 'Mango', translation: 'Golden tropical', translationRu: 'Манго' },
      { word: 'Kiwi', translation: 'Fuzzy green slice', translationRu: 'Киви' },
      { word: 'Strawberry', translation: 'Sweet red heart', translationRu: 'Клубника' },
      { word: 'Pineapple', translation: 'Crown tropical', translationRu: 'Ананас' },
      { word: 'Watermelon', translation: 'Giant striped sweet', translationRu: 'Арбуз' },
      { word: 'Apricot', translation: 'Small peach', translationRu: 'Абрикос' },
      { word: 'Blueberry', translation: 'Tiny blue ball', translationRu: 'Черника' },
      { word: 'Raspberry', translation: 'Pink forest cluster', translationRu: 'Малина' },
      { word: 'Coconut', translation: 'Hard brown nut', translationRu: 'Кокос' },
      { word: 'Grapefruit', translation: 'Big bitter orange', translationRu: 'Грейпфрут' },
      { word: 'Blackberry', translation: 'Dark sweet cluster', translationRu: 'Ежевика' },
      { word: 'Fig', translation: 'Soft purple sweet', translationRu: 'Инжир' },
      { word: 'Lime', translation: 'Sour green', translationRu: 'Лайм' },
      { word: 'Papaya', translation: 'Orange tropical slice', translationRu: 'Папайя' },
      { word: 'Pomegranate', translation: 'Red seed chest', translationRu: 'Гранат' },
      { word: 'Avocado', translation: 'Green cream pear', translationRu: 'Авокадо' },
      { word: 'Cranberry', translation: 'Sour red marsh', translationRu: 'Клюква' },
      { word: 'Tangerine', translation: 'Small sweet orange', translationRu: 'Мандарин' },
      { word: 'Olive', translation: 'Tiny green oil', translationRu: 'Олива' },
      { word: 'Persimmon', translation: 'Sweet orange winter', translationRu: 'Хурма' },
    ],
  },
  {
    id: 'colors',
    name: 'Colors',
    description: 'Beautiful visible light spectrum hues',
    icon: 'palette',
    words: [
      { word: 'Red', translation: 'Fire glow hue', translationRu: 'Красный' },
      { word: 'Blue', translation: 'Clear sky shade', translationRu: 'Синий' },
      { word: 'Green', translation: 'Spring grass tone', translationRu: 'Зелёный' },
      { word: 'Yellow', translation: 'Bright sun paint', translationRu: 'Жёлтый' },
      { word: 'Pink', translation: 'Soft rose glow', translationRu: 'Розовый' },
      { word: 'Purple', translation: 'Royal berry hue', translationRu: 'Фиолетовый' },
      { word: 'White', translation: 'Pure snow shade', translationRu: 'Белый' },
      { word: 'Black', translation: 'Midnight dark look', translationRu: 'Чёрный' },
      { word: 'Brown', translation: 'Warm wood tone', translationRu: 'Коричневый' },
      { word: 'Gray', translation: 'Rain cloud color', translationRu: 'Серый' },
      { word: 'Orange', translation: 'Sunset glow light', translationRu: 'Оранжевый' },
      { word: 'Golden', translation: 'Vibrant metallics', translationRu: 'Золотой' },
      { word: 'Silver', translation: 'Polished white metal', translationRu: 'Серебряный' },
      { word: 'Beige', translation: 'Soft sand tone', translationRu: 'Бежевый' },
      { word: 'Lime', translation: 'Fierce green light', translationRu: 'Лаймовый' },
      { word: 'Violet', translation: 'Soft purple mist', translationRu: 'Сиреневый' },
      { word: 'Indigo', translation: 'Deep night blue', translationRu: 'Индиго' },
      { word: 'Turquoise', translation: 'Sea green shade', translationRu: 'Бирюзовый' },
      { word: 'Cyan', translation: 'Electric sky tint', translationRu: 'Голубой' },
      { word: 'Magenta', translation: 'Deep power pink', translationRu: 'Пурпурный' },
      { word: 'Crimson', translation: 'Rich dark red', translationRu: 'Багровый' },
      { word: 'Lavender', translation: 'Purple flower shade', translationRu: 'Лавандовый' },
      { word: 'Amber', translation: 'Golden gem glow', translationRu: 'Янтарный' },
      { word: 'Maroon', translation: 'Chestnut dark red', translationRu: 'Бордовый' },
      { word: 'Navy', translation: 'Deep sea uniform', translationRu: 'Тёмно-синий' },
      { word: 'Olive', translation: 'Dark green branch', translationRu: 'Оливковый' },
      { word: 'Emerald', translation: 'Green jewel gleam', translationRu: 'Изумрудный' },
      { word: 'Coral', translation: 'Warm ocean pink', translationRu: 'Коралловый' },
      { word: 'Peach', translation: 'Soft orange-cream', translationRu: 'Персиковый' },
      { word: 'Bronze', translation: 'Aged brown metal', translationRu: 'Бронзовый' },
    ],
  },
  {
    id: 'numbers',
    name: 'Numbers',
    description: 'Count items and quantify values',
    icon: 'hash',
    words: [
      { word: 'One', translation: 'Count 1', translationRu: 'Один' },
      { word: 'Two', translation: 'Count 2', translationRu: 'Два' },
      { word: 'Three', translation: 'Count 3', translationRu: 'Три' },
      { word: 'Four', translation: 'Count 4', translationRu: 'Четыре' },
      { word: 'Five', translation: 'Count 5', translationRu: 'Пять' },
      { word: 'Six', translation: 'Count 6', translationRu: 'Шесть' },
      { word: 'Seven', translation: 'Count 7', translationRu: 'Семь' },
      { word: 'Eight', translation: 'Count 8', translationRu: 'Восемь' },
      { word: 'Nine', translation: 'Count 9', translationRu: 'Девять' },
      { word: 'Ten', translation: 'Count 10', translationRu: 'Десять' },
      { word: 'Zero', translation: 'Empty value', translationRu: 'Ноль' },
      { word: 'Eleven', translation: 'Count 11', translationRu: 'Одиннадцать' },
      { word: 'Twelve', translation: 'Count 12', translationRu: 'Двенадцать' },
      { word: 'Twenty', translation: 'Count 20', translationRu: 'Двадцать' },
      { word: 'Hundred', translation: 'Count 100', translationRu: 'Сто' },
      { word: 'Thousand', translation: 'Count 1000', translationRu: 'Тысяча' },
      { word: 'Thirteen', translation: 'Count 13', translationRu: 'Тринадцать' },
      { word: 'Fourteen', translation: 'Count 14', translationRu: 'Четырнадцать' },
      { word: 'Fifteen', translation: 'Count 15', translationRu: 'Пятнадцать' },
      { word: 'Sixteen', translation: 'Count 16', translationRu: 'Шестнадцать' },
      { word: 'Seventeen', translation: 'Count 17', translationRu: 'Семнадцать' },
      { word: 'Eighteen', translation: 'Count 18', translationRu: 'Восемнадцать' },
      { word: 'Nineteen', translation: 'Count 19', translationRu: 'Девятнадцать' },
      { word: 'Thirty', translation: 'Count 30', translationRu: 'Тридцать' },
      { word: 'Forty', translation: 'Count 40', translationRu: 'Сорок' },
      { word: 'Fifty', translation: 'Count 50', translationRu: 'Пятьдесят' },
      { word: 'Sixty', translation: 'Count 60', translationRu: 'Шестьдесят' },
      { word: 'Seventy', translation: 'Count 70', translationRu: 'Семьдесят' },
      { word: 'Eighty', translation: 'Count 80', translationRu: 'Восемьдесят' },
      { word: 'Ninety', translation: 'Count 90', translationRu: 'Девяносто' },
    ],
  },
  {
    id: 'shapes',
    name: 'Shapes',
    description: 'Geometric structures and figures',
    icon: 'heart',
    words: [
      { word: 'Star', translation: 'Night sky light shape', translationRu: 'Звезда' },
      { word: 'Heart', translation: 'Love symbol shape', translationRu: 'Сердце' },
      { word: 'Circle', translation: 'Round ring shape', translationRu: 'Круг' },
      { word: 'Square', translation: 'Four equal sides shape', translationRu: 'Квадрат' },
      { word: 'Triangle', translation: 'Three corners shape', translationRu: 'Треугольник' },
      { word: 'Diamond', translation: 'Sparkling gem shape', translationRu: 'Ромб' },
      { word: 'Rectangle', translation: 'Long box shape', translationRu: 'Прямоугольник' },
      { word: 'Oval', translation: 'Egg line shape', translationRu: 'Овал' },
      { word: 'Hexagon', translation: 'Six corners shape', translationRu: 'Шестиугольник' },
      { word: 'Pentagon', translation: 'Five corners shape', translationRu: 'Пятиугольник' },
      { word: 'Octagon', translation: 'Eight corners shape', translationRu: 'Восьмиугольник' },
      { word: 'Cylinder', translation: 'Can roll shape', translationRu: 'Цилиндр' },
      { word: 'Cone', translation: 'Party hat shape', translationRu: 'Конус' },
      { word: 'Sphere', translation: 'Ball round shape', translationRu: 'Шар' },
      { word: 'Cube', translation: 'Block box shape', translationRu: 'Куб' },
      { word: 'Pyramid', translation: 'Egypt stone shape', translationRu: 'Пирамида' },
      { word: 'Cross', translation: 'Plus sign shape', translationRu: 'Крест' },
      { word: 'Crescent', translation: 'New moon shape', translationRu: 'Полумесяц' },
      { word: 'Arrow', translation: 'Pointer sign shape', translationRu: 'Стрелка' },
      { word: 'Line', translation: 'Straight track shape', translationRu: 'Линия' },
      { word: 'Point', translation: 'Dot sign shape', translationRu: 'Точка' },
      { word: 'Ring', translation: 'Loop finger shape', translationRu: 'Кольцо' },
      { word: 'Box', translation: 'Container square shape', translationRu: 'Коробка' },
      { word: 'Spiral', translation: 'Coil curl shape', translationRu: 'Спираль' },
      { word: 'Wave', translation: 'Ripple curves shape', translationRu: 'Волна' },
      { word: 'Curve', translation: 'Bent line shape', translationRu: 'Кривая' },
      { word: 'Wedge', translation: 'Incline slide shape', translationRu: 'Клин' },
      { word: 'Arc', translation: 'Rainbow bow shape', translationRu: 'Дуга' },
      { word: 'Corner', translation: 'Turn edge shape', translationRu: 'Угол' },
      { word: 'Tube', translation: 'Hollow pipe shape', translationRu: 'Труба' },
    ],
  },
  {
    id: 'nature',
    name: 'Nature',
    description: 'Objects representing our planet and biosphere',
    icon: 'tree',
    words: [
      { word: 'Sun', translation: 'Bright yellow day star', translationRu: 'Солнце' },
      { word: 'Moon', translation: 'White glowing night light', translationRu: 'Луна' },
      { word: 'Rain', translation: 'Falling water clouds', translationRu: 'Дождь' },
      { word: 'Wind', translation: 'Blowing airy breeze', translationRu: 'Ветер' },
      { word: 'Snow', translation: 'Cold white ice flakes', translationRu: 'Снег' },
      { word: 'Tree', translation: 'Tall woody green plant', translationRu: 'Дерево' },
      { word: 'Flower', translation: 'Sweet smelling bloom', translationRu: 'Цветок' },
      { word: 'River', translation: 'Flowing water path', translationRu: 'Река' },
      { word: 'Cloud', translation: 'Fluffy white air pillow', translationRu: 'Облако' },
      { word: 'Sky', translation: 'Deep blue atmosphere', translationRu: 'Небо' },
      { word: 'Forest', translation: 'Lush green dense woods', translationRu: 'Лес' },
      { word: 'Lake', translation: 'Quiet standing water pond', translationRu: 'Озеро' },
      { word: 'Leaf', translation: 'Flat green tree helper', translationRu: 'Лист' },
      { word: 'Grass', translation: 'Green carpet soil lining', translationRu: 'Трава' },
      { word: 'Rainbow', translation: 'Seven color dynamic bow', translationRu: 'Радуга' },
      { word: 'Mountain', translation: 'Giant sloped rock height', translationRu: 'Гора' },
      { word: 'Ocean', translation: 'Huge world water body', translationRu: 'Океан' },
      { word: 'Sea', translation: 'Salty coastline water', translationRu: 'Море' },
      { word: 'Stone', translation: 'Small hard ground piece', translationRu: 'Камень' },
      { word: 'Rock', translation: 'Big solid ancient mass', translationRu: 'Скала' },
      { word: 'Sand', translation: 'Tiny golden shore grains', translationRu: 'Песок' },
      { word: 'Fire', translation: 'Hot glowing yellow flame', translationRu: 'Огонь' },
      { word: 'Wave', translation: 'Curving ocean water wall', translationRu: 'Волна' },
      { word: 'Beach', translation: 'Sunny sandy sea edge', translationRu: 'Пляж' },
      { word: 'Hill', translation: 'Gentle grassy green slope', translationRu: 'Холм' },
      { word: 'Field', translation: 'Flat open grass meadow', translationRu: 'Поле' },
      { word: 'Storm', translation: 'Loud rainy wind dark', translationRu: 'Шторм' },
      { word: 'Ice', translation: 'Frozen solid cool water', translationRu: 'Лёд' },
      { word: 'Bud', translation: 'Unopened baby flower', translationRu: 'Бутон' },
      { word: 'Bush', translation: 'Dense short leafy plant', translationRu: 'Куст' },
    ],
  },
  {
    id: 'short_phrases',
    name: 'Short Phrases',
    description: 'Learn simple English greeting and social phrases',
    icon: 'message-square',
    words: [
      { word: 'How are you?', translation: 'Asking about health', translationRu: 'Как дела?' },
      { word: 'Nice to meet you', translation: 'Friendly greeting', translationRu: 'Приятно познакомиться' },
      { word: 'Good morning', translation: 'Morning greeting', translationRu: 'Доброе утро' },
      { word: 'Have a nice day', translation: 'Polite wish', translationRu: 'Хорошего дня' },
      { word: 'Thank you very much', translation: 'Gratitude expression', translationRu: 'Большое спасибо' },
      { word: 'See you later', translation: 'Parting words', translationRu: 'Увидимся позже' },
      { word: 'What is your name?', translation: 'Asking for identity', translationRu: 'Как тебя зовут?' },
      { word: 'Excuse me', translation: 'Polite attention grabber', translationRu: 'Прошу прощения' },
      { word: 'You are welcome', translation: 'Response to thanks', translationRu: 'Пожалуйста' },
      { word: 'I do not know', translation: 'Lack of info', translationRu: 'Я не знаю' },
    ],
  },
  {
    id: 'long_phrases',
    name: 'Long Phrases',
    description: 'Practice longer sentences to boost pronunciation confidence',
    icon: 'book-open',
    words: [
      { word: 'The weather is beautiful today', translation: 'Sunny climate talk', translationRu: 'Сегодня прекрасная погода' },
      { word: 'I love playing educational voice games', translation: 'Fun learning preference', translationRu: 'Я люблю играть в обучающие голосовые игры' },
      { word: 'Can you please help me with this?', translation: 'Polite request', translationRu: 'Не мог бы ты помочь мне с этим?' },
      { word: 'My favorite color is bright blue', translation: 'Personal preference', translationRu: 'Мой любимый цвет - ярко-синий' },
      { word: 'The quick brown fox jumps over the lazy dog', translation: 'Famous pangram', translationRu: 'Быстрая бурая лиса прыгает через ленивую собаку' },
      { word: 'Practice makes perfect in language learning', translation: 'Motivational wisdom', translationRu: 'Практика делает мастера в изучении языков' },
      { word: 'I am ready to fly my rocket into deep space', translation: 'Space mission spirit', translationRu: 'Я готов запустить свою ракету в открытый космос' },
      { word: 'An apple a day keeps the doctor away', translation: 'Healthy proverb', translationRu: 'Кто яблоко в день съедает, у того доктор не бывает' },
      { word: 'Let us read a story before going to sleep', translation: 'Bedtime routine', translationRu: 'Давай почитаем сказку перед сном' },
      { word: 'Brave explorers are not afraid of the dark', translation: 'Encouraging courage', translationRu: 'Смелые исследователи не боятся темноты' },
      { word: 'Every new word makes you a little smarter', translation: 'Learning motivation', translationRu: 'Каждое новое слово делает тебя немного умнее' },
    ],
  },
];
