import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';

export type UiLanguage = 'en' | 'ru';

interface UiLanguageContextValue {
  language: UiLanguage;
  setLanguage: (language: UiLanguage) => void;
  t: (path: string) => string;
}

interface TranslationDictionary {
  [key: string]: string | TranslationDictionary;
}

const STORAGE_KEY = 'ui_language';

const UI_TEXT: Record<UiLanguage, TranslationDictionary> = {
  en: {
    header: {
      title: 'VOICE GAMES',
      subtitle: '⭐ KIDS LEARNING HUB',
      totalRecord: 'TOTAL RECORD:',
      backToHub: 'HUB',
      score: 'SCORE:',
      best: 'BEST:',
      total: 'TOTAL:',
      level: 'Level',
      switchLabel: 'Switch interface language to Russian',
      switchToRussian: 'RU',
      switchToEnglish: 'EN',
    },
    hub: {
      title: 'VOICE GAMES!',
      subtitle: 'Play English games with your voice! Match words, pop balloons, and win trophies!',
      playBadge: 'PLAY',
      lockedBadge: 'TEMPLATE',
      record: 'RECORD:',
      playButton: 'PLAY',
    },
    games: {
      voiceRacer: {
        title: 'VOICE LANE RACER',
        description: 'Pronounce words right to avoid car crashing! Correct pronunciation swerves your car to dodge roadblocks.',
      },
      bubblePopper: {
        title: 'VOICE BUBBLE POPPER',
        description: 'Pronounce words on translucent floating bubbles to pop them before they cross the red danger zone!',
      },
      bossFight: {
        title: 'BOSS FIGHT',
        description: 'Say each English word to strike the boss! Beat one boss and a tougher one appears - survive as long as you can, and watch the timer on every word.',
      },
      wordLadder: {
        title: 'VOICE ROCKET CLIMB',
        description: 'Pronounce words correctly to launch your rocket higher and higher! Reach orbit to win!',
        winTitle: 'Orbit reached! 🚀',
        winDescription: 'You boosted your rocket through all {total} stages into deep space!',
        sayToLaunch: 'Say this word to boost',
        again: 'Again',
      },
      treasureHunter: {
        title: 'VOICE TREASURE HUNTER',
        description: 'Guide the submarine and collect treasure chests from the ocean depths by pronouncing words correctly!',
      },
      sentenceBird: {
        title: 'Sentence Bird',
        description: 'Speak sentence steps aloud to guide the bird through the clouds and grow your pronunciation confidence.',
      },
      echoRecorder: {
        title: 'Echo Microphone',
        description: 'Listen to word sequences and repeat them back to grow the chain and train your pronunciation memory!',
      },
    },
    shared: {
      chooseWordSet: 'Choose a word set',
      listenAndLearn: 'Listen and learn',
      myWords: 'My Words',
      customWords: 'Custom Words List',
      start: 'Start',
      startFight: 'Start Fight',
      startClimb: 'Start Launch',
      startPopping: 'START POPPING!',
      backToHub: 'Hub',
      learnAndPractice: 'Learn and practice',
      customWordsBuilder: 'Custom words builder',
      emptyCustomList: 'Your custom dictionary list is currently empty!',
      emptyCustomListBubble: 'Your custom list is currently empty!',
      startHighwayRace: 'START HIGHWAY RACE!',
      chooseRoadEnvironment: 'CHOOSE ROAD ENVIRONMENT:',
      taskBook: 'TASK BOOK:',
      listenAndLearnPractice: 'LISTEN & LEARN PRACTICE',
      wordsLabel: 'words',
      customListEmpty: 'No words registered yet. Tap start to play again.',
      chooseMissionTheme: 'CHOOSE MISSION THEME:',
      chooseArenaTheme: 'CHOOSE ARENA THEME:',
      addMyOwnWords: 'ADD MY OWN WORDS',
      preview: 'Preview',
      hearWord: 'Hear the word',
      listenInRussian: 'Listen in Russian',
      listenEnglish: 'Listen (EN)',
      listenRussian: 'Listen (RU)',
      targetRibbon: 'Say this word',
      youSaidHeard: 'You said / Heard:',
      pause: 'Pause',
      resume: 'Resume',
      paused: 'Paused',
      pauseGame: 'Pause the game',
      resumeGame: 'Resume the game',
      backToHubAria: 'Back to hub',
      micListening: '🎤 Mic is listening...',
      micAccessBlocked: 'Microphone access blocked. Please allow mic access in your browser address bar!',
      voiceStartPrompt: 'Click Start to turn on the microphone.',
      voiceUnsupported: 'Google Chrome Voice API not detected. Please play inside Google Chrome!',
      voiceEngineLive: 'Voice engine live! Speak the English words aloud!',
      voiceStopped: 'Voice engine stopped.',
      quit: 'Quit game',
      greatSpeaking: 'GREAT SPEAKING!',
      perfectSpeech: 'Perfect pronunciation feedback is ready.',
      error: 'Error:',
      microphoneOff: 'MICROPHONE OFF',
      speakTarget: 'Speak the target English word aloud.',
      microphoneOffPrompt: 'Click Start in the menu to turn on the microphone.',
      wordsHeard: 'Words heard:',
      voiceNeedsChrome: 'Voice control needs Google Chrome. Please open the game in Chrome.',
      lives: 'Lives',
      best: 'Best',
      clear: 'Clear',
      listen: 'Listen',
      neonGridActive: 'Neon grid active',
      progress: 'Progress',
      openProgress: 'Open progress',
      clues: 'Clues',
      exitToPortal: 'Exit to portal',
      back: 'Back',
    },
    racer: {
      sayToJump: 'Say an English word loudly to jump lanes!',
      drivingScore: 'Driving score',
      recordTarget: 'Record target',
      voiceEngineLive: 'Voice engine live! Speak the English words aloud!',
      sayWordToDodge: 'SAY WORD TO DODGE!',
      topic: 'Topic',
      speakQuickly: 'SPEAK QUICKLY IN ORDER TO SWERVE!',
      leftLane: 'LEFT LANE',
      centerLane: 'CENTER',
      rightLane: 'RIGHT LANE',
      finishLine: 'Driving Finish Line!',
      gameOverTitle: 'SUPER COOPER DRIVING!',
      gameOverDescription: 'You drove amazingly! Click below to practice speaking words and beat your high record!',
      points: 'points',
      practiceScorecard: 'Your English Practice Scorecard:',
      emptyScorecard: 'Spoken scorecard empty. Try driving again to gather speech stats!',
      playAgain: 'PLAY HIGHWAY AGAIN!',
      options: 'Race Options',
      heard: 'Heard',
    },
    boss: {
      battleLength: 'Battle length:',
      bosses: 'Bosses',
      endless: 'Endless',
      endlessTitle: 'Endless Boss Fight',
      unlockHint: 'Beat a boss fight once to unlock!',
      endlessDescription: 'Fight an endless horde of bosses! Say each English word aloud and survive as long as you can.',
      beatPrefix: 'Beat',
      beatSuffix: 'bosses by saying each English word before the timer ends!',
      unlockTip: 'Tip: Beat any mode to unlock Endless mode!',
      boss: 'Boss',
      totalHits: 'total hits this battle',
      health: 'Boss health',
      victory: 'VICTORY!',
      battleConcluded: 'BATTLE CONCLUDED!',
      youWon: 'YOU WON!',
      gameOver: 'GAME OVER!',
      report: 'Review your English combat stats below:',
      wordsSmashed: 'WORDS SMASHED',
      personalHigh: 'PERSONAL HIGH',
      scorecard: 'Your spelling scorecard:',
      emptyReport: 'No words registered yet. Start the fight to practice!',
      hits: 'Hits',
      fightAgain: 'Fight Again!',
    },
    ladder: {
      altitude: 'Altitude meters',
      personalHigh: 'Personal high',
      scorecard: 'Your spelling scorecard:',
      emptyReport: 'No words registered yet. Launch the rocket to practice!',
      boost: 'Boost',
      sayHello: 'Say hello to the alien',
      alienEncounter: 'Alien encounter',
      alienDescription: 'A friendly alien is waving from orbit.',
      alienGreeting: 'The alien says: “You did it! Keep practicing and your rocket will shine brighter.”',
      steps: 'steps',
    },
    wordSets: {
      animals: 'Animals',
      fruits: 'Fruits',
      colors: 'Colors',
      numbers: 'Numbers',
      shapes: 'Shapes',
      nature: 'Nature',
      short_phrases: 'Short Phrases',
      long_phrases: 'Long Phrases',
      custom: 'My Words',
    },
    customWords: {
      englishRequired: 'Please write an English word or phrase!',
      translationRequired: 'Please add the translation!',
      invalidCharacters: 'Letters, numbers, spaces and standard punctuation only!',
      englishLabel: 'English word or phrase:',
      englishPlaceholder: 'e.g. Nice to meet you!',
      translationLabel: 'Translation:',
      translationPlaceholder: 'e.g. Приятно познакомиться!',
      addButton: 'Add to my list!',
      dictionaryTitle: 'My custom dictionary',
      clearAll: 'Clear all',
      empty: 'Your dictionary is empty. Add an English word and its translation above!',
      speakWord: 'Speak word',
      deleteWord: 'Delete word',
      bulkTitle: 'Paste many at once',
      bulkHint: 'One pair per line, separated by | or ;',
      bulkPlaceholder: 'hello | привет\ngood morning | доброе утро',
      bulkButton: 'Import list',
      bulkResult: 'Added {added}. Skipped {skipped} invalid line(s).',
      bulkEmpty: 'No valid pairs found. Use one "word | translation" per line.',
    },
    aste: {
      title: 'AsteWord Destroyer',
      description: 'Destroy the slowly falling asteroids by saying the English words written on them! ☄️',
      start: 'Start Defense',
      score: 'Destroyed',
      best: 'Best Score',
      paused: 'Paused',
      resume: 'Resume',
      pause: 'Pause',
      chooseSet: 'Choose Word Set',
      myWords: 'My Words',
      chooseTheme: 'CHOOSE SPACE SECTOR THEME:',
      chooseDifficulty: 'CHOOSE DIFFICULTY LEVEL:',
      easy: 'Easy 🟢',
      medium: 'Medium 🟡',
      hard: 'Hard 🔴',
      shield: 'Shield',
      activeTargets: '🎯 ACTIVE TARGETS (CLICK TO HEAR):',
      waitingTargets: 'Waiting for asteroids to enter the sector...',
      lasers: 'lasers',
      sessionOver: 'SECTOR DEFENSE OVER!',
      gameOver: 'GAME OVER!',
      report: 'Review your cosmic asteroid spelling stats below:',
      destroyedTotal: 'ASTEROIDS CRUSHED',
      galaxyRecord: 'GALAXY RECORD',
      scorecard: 'Your spelling scorecard:',
      emptyReport: 'No asteroids destroyed yet. Fire those lasers!',
      kills: 'Kills',
    },
    skate: {
      title: 'SkateWord Park',
      description: 'Ride through the park! Speak the words in time to jump and collect stars! 🛹',
      start: 'Start Skating',
      score: 'Stars',
      best: 'Best Score',
      paused: 'Paused',
      resume: 'Resume',
      pause: 'Pause',
      chooseSet: 'Choose Word Set',
      myWords: 'My Words',
      sayThis: '🎯 SPEAK TO DO A FLIP!:',
      chooseTheme: 'CHOOSE SKATE PARK ENVIRONMENT:',
      sessionOver: 'SKATE SESSION OVER!',
      gameOver: 'GAME OVER!',
      report: 'Review your skateboard spelling stats below:',
      starsCollected: 'STARS COLLECTED',
      parkRecord: 'PARK RECORD',
      scorecard: 'Your spelling scorecard:',
      emptyReport: 'No words flipped yet. Start skating to practice!',
      flips: 'Flips',
    },
    treasure: {
      title: 'Voice Treasure Hunter',
      description: 'Steer the submarine! Pronounce words correctly to dive deeper and collect treasure chests! 🐳',
      start: 'Start Diving',
      score: 'Chests',
      best: 'Best Score',
      paused: 'Paused',
      resume: 'Resume',
      pause: 'Pause',
      chooseSet: 'Choose Word Set',
      myWords: 'My Words',
      sayThis: '🎯 PRONOUNCE TO DIVE!:',
      chooseTheme: 'CHOOSE SUBMARINE COLOR:',
      diveCompleted: 'DIVE COMPLETED!',
      totalChests: 'TOTAL CHESTS',
      bestRecord: 'BEST RECORD',
      scorecard: 'Dive spelling scorecard:',
      emptyReport: 'No chests collected yet.',
      correct: 'Chests',
      missed: 'Missed',
      depth: 'DEPTH',
    },
    wizard: {
      title: 'Magic Wizard',
      description: 'Cast powerful elemental spells! Pronounce target words correctly to defeat approaching monsters! 🧙‍♂️✨',
      start: 'Begin Spellcasting',
      score: 'Monsters Defeated',
      best: 'Best Score',
      paused: 'Paused',
      resume: 'Resume',
      pause: 'Pause',
      chooseSet: 'Choose Word Set',
      myWords: 'My Words',
      sayThis: '🎯 SPEAK TO CAST SPELL!:',
      chooseTheme: 'CHOOSE WIZARD SPELL ELEMENT:',
      gameOverTitle: 'WIZARD BATTLE OVER!',
      gameOverSubtitle: 'The magical portal has closed. Your wizard battle stats:',
      playAgain: 'Play Again',
    },
    sentenceBird: {
      title: 'Sentence Bird',
      subtitle: 'Speak one word to fly through each pipe.',
      startLabel: 'Start flying',
      score: 'Score',
      best: 'Best',
      completed: 'Done',
      chooseSet: 'Choose Word Set',
      myWords: 'My Words',
      chooseTheme: 'Choose sky theme',
      targetRibbon: 'Say this word',
      ready: 'Ready to listen.',
      detected: 'Detected',
      completedTitle: 'You did it, champion!',
      completedText: 'You flew through every word in this set.',
      failureTitle: 'Oh no, crashed!',
      failureText: 'You ran out of lives. Try again!',
      playAgain: 'Play again',
      back: 'Back to hub',
      world: 'World',
      emptySet: 'Add words to My Words or choose a built-in set.',
      wordsMastered: 'Words mastered:',
      accuracy: 'Accuracy',
      speakLabel: 'Say it!',
    },
    echo: {
      title: 'Echo Microphone',
      subtitle: 'Listen and repeat the chain!',
      back: 'Back to hub',
      start: 'Start Level',
      chooseLevel: 'Choose difficulty',
      chooseTheme: 'Choose echo theme',
      levelOne: 'Everyday words',
      levelTwo: 'Short phrases',
      levelThree: 'Idioms',
      best: 'Best',
      howToPlay: 'How to play',
      learnRules: 'Learn Rules',
      lobbyTitle: 'Echo Microphone',
      lobbyIntro: 'Listen to the sequence carefully, then repeat it in the same order to grow the chain!',
      lobbyStepOne: 'Listen to each word in the sequence.',
      lobbyStepTwo: 'Repeat the words in order.',
      lobbyStepThree: 'Grow the chain and complete the level!',
      listening: 'Listening phase: Pay attention to pronunciation...',
      speaking: 'Speak now: Repeat the terms in order!',
      replay: 'Replay Voice Guidance',
      currentChain: 'Current Chain',
      levelTarget: 'Level Target',
      bestChain: 'Best Chain',
      perfectMatch: 'Perfect Memory Echo!',
      perfectDesc: 'Your sequence order and pronunciation were flawless. Get ready for a longer chain!',
      growChain: 'Grow Chain',
      proceed: 'Proceed to Level',
      restart: 'Restart Chain',
      victory: 'ECHO MICROPHONE COMPLETED!',
      victoryDesc: 'Incredible performance! You completed all voice-chain levels.',
      replayAll: 'Replay All Levels',
      tryAgain: 'Try Again!',
      missedAt: 'You missed at word',
      startOver: "Let's start the sequence over!",
      phonetic: 'Phonetic',
      score: 'Score',
      completed: 'Done',
      chainWords: 'Words',
      pts: 'pts',
      word: 'Word',
      translation: 'Translation',
      target: 'Target',
      memoryCard: 'MEMORY CARD',
      sayNext: 'SAY NEXT',
      idle: 'Transceiver Idle',
      voiceActive: 'Voice Active',
      muted: 'Receiver Muted',
      guide: 'Guide',
      words: 'words',
      level: 'Level',
      speakLabel: 'Speak!',
      voiceFeed: 'Voice Feed',
      pronRef: 'Pronunciation Reference',
      supremeMaster: 'Supreme Memory Master!',
      finalScore: 'Final Score',
      longestChainLabel: 'Longest Chain',
      totalAttemptsLabel: 'Total Attempts',
      correctRoundsLabel: 'Correct Rounds',
      lives: 'Lives',
      gameOverBadge: 'Out of hearts',
      gameOverTitle: 'GAME OVER',
      gameOverDesc: 'You stumbled three times. Great memory work - try again to beat your chain!',
      playAgain: 'Play Again',
      previewWord: 'Word',
      themes: {
        studio: '🎧 Studio',
        forest: '🌲 Forest',
        space: '🪐 Space',
      },
      levels: {
        1: { subtitle: 'Everyday words' },
        2: { subtitle: 'Short phrases' },
        3: { subtitle: 'Idioms and tongue twisters' },
      },
    },
    themes: {
      racer: {
        forest: '🌲 Forest Land',
        night: '🌌 Cosmic Night',
        desert: '🏜️ Golden Desert',
        city: '🏎️ Neon City',
      },
      ladder: {
        earth: '🌍 Earth Orbit',
        mars: '🔴 Flight to Mars',
        nebula: '🌌 Alien Nebula',
      },
      bubble: {
        sky: '☁️ Drifting Clouds',
        snow: '❄️ Snowy Wilderness',
        starry: '🌙 Moonlit Sparkles',
        nebula: '🌌 Cosmic Galaxies',
      },
      boss: {
        castle: '🏰 Castle Ruins',
        lava: '🌋 Lava Dungeon',
        forest: '🌲 Magic Forest',
        abyss: '🌌 Void Abyss',
      },
      aste: {
        galaxy: '🌌 Galaxy',
        supernova: '☀️ Supernova',
        aurora: '🌈 Aurora',
      },
      skate: {
        forest: '🌲 Forest',
        sunset: '🌇 Sunset',
        neon: '🌃 Neon',
      },
      treasure: {
        yellow: '🟡 Yellow',
        orange: '🟠 Orange',
        cyan: '🔵 Cyan',
        neon: '🟢 Neon',
      },
      wizard: {
        fire: '🔥 Fire',
        ice: '❄️ Ice',
        lightning: '⚡ Lightning',
      },
      sentenceBird: {
        forest: '🌲 Forest',
        winter: '❄️ Winter',
        space: '🌌 Space',
        ninja: '🥷 Ninja Night',
      },
    },
    bubble: {
      gameSelected: 'Game Selected',
      title: 'Voice Bubble Popper',
      hubPortal: 'Hub Portal',
      chooseSkyAtmosphere: 'CHOOSE SKY ATMOSPHERE THEME:',
      wordListTopic: 'WORD LIST TOPIC:',
      listenAndPractice: 'LISTEN & PRACTICE',
      customWordsBuilder: 'CUSTOM WORDS BUILDER',
      gameOverTitle: 'SUPER BUBBLES POPPING!',
      gameOverSubtitle: 'Speech bubble pop-out concluded! Review your English scoring below:',
      poppingScore: 'POPPING SCORE',
      personalHigh: 'PERSONAL HIGH',
      scoreCard: 'Your Spelling Scorecard:',
      playAgain: 'Popping Again!',
      bubbleOptions: 'Bubble Options',
      exitToPortal: 'EXIT TO GAMES PORTAL',
      wordsHeard: 'Words Heard:',
      sayAnyWord: 'Say any word written on the bubbles!',
      words: 'WORDS:',
      quit: 'QUIT',
      points: 'PTS:',
      clueLabel: 'Clues:',
      poppedLabel: 'Popped:',
      listenInRussian: 'Listen in Russian',
      hearWord: 'Hear the word',
      voiceEngineLive: 'Voice engine live! Speak the English words to pop bubbles!',
    },
  },
  ru: {
    header: {
      title: 'ГОЛОСОВЫЕ ИГРЫ',
      subtitle: '⭐ ЦЕНТР ИГР ДЛЯ ДЕТЕЙ',
      totalRecord: 'СУММА РЕКОРДОВ:',
      backToHub: 'ХАБ',
      score: 'СЧЁТ:',
      best: 'РЕКОРД:',
      total: 'ВСЕГО:',
      level: 'Уровень',
      switchLabel: 'Switch interface language to English',
      switchToRussian: 'RU',
      switchToEnglish: 'EN',
    },
    hub: {
      title: 'ГОЛОСОВЫЕ ИГРЫ!',
      subtitle: 'Играй в английские игры голосом! Подбирай слова, лопай шарики и побеждай!',
      playBadge: 'ИГРАТЬ',
      lockedBadge: 'ШАБЛОН',
      record: 'РЕКОРД:',
      playButton: 'ИГРАТЬ',
    },
    games: {
      voiceRacer: {
        title: 'ГОЛОСОВАЯ ГОНКА',
        description: 'Произноси слова правильно, чтобы не влететь в аварии! Верное произношение помогает уйти от препятствий.',
      },
      bubblePopper: {
        title: 'ЛОПАНИЕ ПУЗЫРЕЙ',
        description: 'Произноси слова на прозрачных пузырях, чтобы успеть их лопнуть до красной зоны опасности!',
      },
      bossFight: {
        title: 'БОЙ С БОССОМ',
        description: 'Произноси каждое английское слово, чтобы бить босса! Победишь одного - приходит посильнее. Держись как можно дольше и следи за таймером.',
      },
      wordLadder: {
        title: 'КОСМИЧЕСКИЙ СТАРТ',
        description: 'Произноси слова правильно, чтобы запустить ракету в космос! Доберись до орбиты для победы!',
        winTitle: 'Орбита достигнута! 🚀',
        winDescription: 'Ты успешно вывел ракету на все {total} ступеней в открытый космос!',
        sayToLaunch: 'Произнеси слово для запуска',
        again: 'Заново',
      },
      treasureHunter: {
        title: 'ПОИСК СОКРОВИЩ',
        description: 'Управляй подводной лодкой и собирай сундуки с сокровищами на глубине океана, правильно произнося слова!',
      },
      sentenceBird: {
        title: 'Фразоптичка',
        description: 'Произноси части предложений вслух, чтобы вести птичку по облакам и тренировать произношение.',
      },
      echoRecorder: {
        title: 'Эхо-микрофон',
        description: 'Слушай последовательности слов и повторяй их, чтобы удлинить цепочку и тренировать память произношения!',
      },
    },
    shared: {
      chooseWordSet: 'Выбери набор слов',
      listenAndLearn: 'Слушай и учись',
      myWords: 'Мои слова',
      customWords: 'Список своих слов',
      start: 'Старт',
      startFight: 'Начать бой',
      startClimb: 'Начать запуск',
      startPopping: 'НАЧАТЬ ЛОПАТЬ!',
      backToHub: 'ХАБ',
      learnAndPractice: 'Учись и практикуйся',
      customWordsBuilder: 'Конструктор слов',
      emptyCustomList: 'Список твоих слов пока пуст!',
      emptyCustomListBubble: 'Твой список слов пока пуст!',
      startHighwayRace: 'НАЧАТЬ ГОНКУ!',
      chooseRoadEnvironment: 'ВЫБЕРИ ТЕМУ ДОРОГИ:',
      taskBook: 'КНИЖКА ЗАДАНИЙ:',
      listenAndLearnPractice: 'СЛУШАЙ И УЧИСЬ',
      wordsLabel: 'слов',
      customListEmpty: 'Слов ещё нет. Нажми старт, чтобы сыграть снова.',
      chooseMissionTheme: 'ВЫБЕРИ ТЕМУ МИССИИ:',
      chooseArenaTheme: 'ВЫБЕРИ ТЕМУ АРЕНЫ:',
      addMyOwnWords: 'ДОБАВИТЬ СВОИ СЛОВА',
      preview: 'Предпросмотр',
      hearWord: 'Послушать слово',
      listenInRussian: 'Слушать по-русски',
      listenEnglish: 'Слушать (EN)',
      listenRussian: 'Слушать (RU)',
      targetRibbon: 'Произнеси слово',
      youSaidHeard: 'Вы сказали / Слышу:',
      pause: 'Пауза',
      resume: 'Продолжить',
      paused: 'Пауза',
      pauseGame: 'Поставить игру на паузу',
      resumeGame: 'Продолжить игру',
      backToHubAria: 'Назад в хаб',
      micListening: '🎤 Микрофон слушает...',
      micAccessBlocked: 'Доступ к микрофону заблокирован. Разреши микрофон в адресной строке браузера!',
      voiceStartPrompt: 'Нажми «Старт», чтобы включить микрофон.',
      voiceUnsupported: 'Голосовое управление Chrome не найдено. Открой игру в Google Chrome!',
      voiceEngineLive: 'Голосовой движок запущен! Произноси английские слова вслух!',
      voiceStopped: 'Голосовой движок остановлен.',
      quit: 'Выйти из игры',
      greatSpeaking: 'ОТЛИЧНОЕ ПРОИЗНОШЕНИЕ!',
      perfectSpeech: 'Отлично! Произношение распознано.',
      error: 'Ошибка:',
      microphoneOff: 'МИКРОФОН ВЫКЛЮЧЕН',
      speakTarget: 'Произнеси английское слово вслух.',
      microphoneOffPrompt: 'Нажми «Старт» в меню, чтобы включить микрофон.',
      wordsHeard: 'Произнесённые слова:',
      voiceNeedsChrome: 'Для голосового управления нужен Google Chrome. Открой игру в Chrome.',
      lives: 'Жизни',
      best: 'Рекорд',
      clear: 'Очистить',
      listen: 'Слушать',
      neonGridActive: 'Неоновая сеть активна',
      progress: 'Прогресс',
      openProgress: 'Открыть прогресс',
      clues: 'Подсказки',
      exitToPortal: 'Выйти в хаб',
      back: 'Назад',
    },
    racer: {
      sayToJump: 'Громко произнеси английское слово, чтобы сменить полосу!',
      drivingScore: 'Очки гонки',
      recordTarget: 'Цель рекорда',
      voiceEngineLive: 'Голосовой движок запущен! Произноси английские слова вслух!',
      sayWordToDodge: 'ПРОИЗНЕСИ СЛОВО, ЧТОБЫ УВЕРНУТЬСЯ!',
      topic: 'Тема',
      speakQuickly: 'ГОВОРИ БЫСТРЕЕ, ЧТОБЫ СВЕРНУТЬ!',
      leftLane: 'ЛЕВАЯ ПОЛОСА',
      centerLane: 'ЦЕНТР',
      rightLane: 'ПРАВАЯ ПОЛОСА',
      finishLine: 'Финиш гонки!',
      gameOverTitle: 'СУПЕР-ГОНКА ЗАВЕРШЕНА!',
      gameOverDescription: 'Ты отлично проехал! Нажми ниже, чтобы потренировать слова и побить свой рекорд!',
      points: 'очков',
      practiceScorecard: 'Твоя таблица практики английского:',
      emptyScorecard: 'Таблица пока пуста. Сыграй ещё раз, чтобы собрать статистику!',
      playAgain: 'СЫГРАТЬ ЕЩЁ РАЗ!',
      options: 'Настройки гонки',
      heard: 'Услышано',
    },
    boss: {
      battleLength: 'Длительность битвы:',
      bosses: 'боссов',
      endless: 'Бесконечно',
      endlessTitle: 'Бесконечный бой',
      unlockHint: 'Победи хотя бы раз, чтобы открыть этот режим!',
      endlessDescription: 'Сражайся с бесконечной ордой боссов! Произноси английские слова и держись как можно дольше.',
      beatPrefix: 'Победи',
      beatSuffix: 'боссов, произнося английские слова до конца таймера!',
      unlockTip: 'Совет: победи в любом режиме, чтобы открыть бесконечный бой!',
      boss: 'Босс',
      totalHits: 'всего ударов за бой',
      health: 'Здоровье босса',
      victory: 'ТЫ ПОБЕДИЛ!',
      battleConcluded: 'БИТВА ЗАВЕРШЕНА!',
      youWon: 'ПОБЕДА!',
      gameOver: 'КОНЕЦ ИГРЫ!',
      report: 'Твой боевой отчёт по английским словам:',
      wordsSmashed: 'УДАРОВ НАНЕСЕНО',
      personalHigh: 'ЛИЧНЫЙ РЕКОРД',
      scorecard: 'Твой боевой отчёт:',
      emptyReport: 'Слов ещё нет. Начни бой, чтобы потренироваться!',
      hits: 'Ударов',
      fightAgain: 'Сражаться снова!',
    },
    ladder: {
      altitude: 'Высота полёта',
      personalHigh: 'Личный рекорд',
      scorecard: 'Космический отчёт:',
      emptyReport: 'Слов ещё нет. Начни полёт, чтобы потренироваться!',
      boost: 'Полёт',
      sayHello: 'Поздороваться с пришельцем',
      alienEncounter: 'Встреча с пришельцем',
      alienDescription: 'Дружелюбный пришелец машет тебе с орбиты.',
      alienGreeting: 'Пришелец говорит: «У тебя получилось! Продолжай тренироваться, и твоя ракета засияет ярче».',
      steps: 'ступеней',
    },
    wordSets: {
      animals: 'Животные',
      fruits: 'Фрукты',
      colors: 'Цвета',
      numbers: 'Числа',
      shapes: 'Фигуры',
      nature: 'Природа',
      short_phrases: 'Короткие фразы',
      long_phrases: 'Длинные фразы',
      custom: 'Мои слова',
    },
    customWords: {
      englishRequired: 'Напиши английское слово или фразу!',
      translationRequired: 'Добавь перевод!',
      invalidCharacters: 'Используй только буквы, цифры, пробелы и обычные знаки препинания!',
      englishLabel: 'Английское слово или фраза:',
      englishPlaceholder: 'например, Nice to meet you!',
      translationLabel: 'Перевод:',
      translationPlaceholder: 'например, Приятно познакомиться!',
      addButton: 'Добавить в мой список!',
      dictionaryTitle: 'Мой словарь',
      clearAll: 'Очистить всё',
      empty: 'Твой словарь пуст. Добавь английское слово и перевод выше!',
      speakWord: 'Озвучить слово',
      deleteWord: 'Удалить слово',
      bulkTitle: 'Вставить сразу много',
      bulkHint: 'Одна пара в строке, разделитель | или ;',
      bulkPlaceholder: 'hello | привет\ngood morning | доброе утро',
      bulkButton: 'Импортировать список',
      bulkResult: 'Добавлено: {added}. Пропущено строк с ошибкой: {skipped}.',
      bulkEmpty: 'Не найдено ни одной пары. Формат: «слово | перевод» на строку.',
    },
    aste: {
      title: 'АстеВорд Разрушитель',
      description: 'Уничтожай медленно летящие астероиды, произнося написанные на них английские слова! ☄️',
      start: 'Начать оборону',
      score: 'Сбито',
      best: 'Рекорд',
      paused: 'Пауза',
      resume: 'Продолжить',
      pause: 'Пауза',
      chooseSet: 'Выбрать набор слов',
      myWords: 'Мои слова',
      chooseTheme: 'ВЫБЕРИ КОСМИЧЕСКИЙ СЕКТОР:',
      chooseDifficulty: 'ВЫБЕРИ УРОВЕНЬ СЛОЖНОСТИ:',
      easy: 'Легкий 🟢',
      medium: 'Средний 🟡',
      hard: 'Сложный 🔴',
      shield: 'Щит',
      activeTargets: '🎯 ТЕКУЩИЕ ЦЕЛИ (НАЖМИ ДЛЯ ОЗВУЧКИ):',
      waitingTargets: 'Ожидание появления астероидов...',
      lasers: 'выстрелов',
      sessionOver: 'СЕКТОР ЗАЩИЩЕН!',
      gameOver: 'КОНЕЦ ИГРЫ!',
      report: 'Твой космический отчёт по сбитым астероидам:',
      destroyedTotal: 'СБИТО АСТЕРОИДОВ',
      galaxyRecord: 'РЕКОРД ГАЛАКТИКИ',
      scorecard: 'Словарь космо-сектора:',
      emptyReport: 'Астероидов не сбито. Защити планету в следующий раз!',
      kills: 'Сбито',
    },
    skate: {
      title: 'СкейтВорд Парк',
      description: 'Катайся по парку! Произноси слова вовремя, чтобы делать прыжки и собирать звезды! 🛹',
      start: 'Встать на скейт',
      score: 'Звезды',
      best: 'Рекорд',
      paused: 'Пауза',
      resume: 'Продолжить',
      pause: 'Пауза',
      chooseSet: 'Выбрать набор слов',
      myWords: 'Мои слова',
      sayThis: '🎯 ПРОИЗНЕСИ ДЛЯ ТРЮКА!:',
      chooseTheme: 'ВЫБЕРИ ОКРУЖЕНИЕ ПАРКА:',
      sessionOver: 'ЗАЕЗД ЗАВЕРШЕН!',
      gameOver: 'КОНЕЦ ИГРЫ!',
      report: 'Твой отчёт о трюках на скейтборде:',
      starsCollected: 'СОБРАНО ЗВЕЗД',
      parkRecord: 'РЕКОРД ПАРКА',
      scorecard: 'Словарь скейт-парка:',
      emptyReport: 'Трюков со словами не выполнено. Попробуй ещё раз!',
      flips: 'Трюков',
    },
    treasure: {
      title: 'Поиск Сокровищ',
      description: 'Управляй подлодкой! Произноси слова правильно, чтобы погружаться глубже и собирать сундуки! 🐳',
      start: 'Начать погружение',
      score: 'Сундуки',
      best: 'Рекорд',
      paused: 'Пауза',
      resume: 'Продолжить',
      pause: 'Пауза',
      chooseSet: 'Выбрать набор слов',
      myWords: 'Мои слова',
      sayThis: '🎯 ПРОИЗНЕСИ ДЛЯ ПОГРУЖЕНИЯ!:',
      chooseTheme: 'ЦВЕТ ПОДВОДНОЙ ЛОДКИ:',
      diveCompleted: 'ПОГРУЖЕНИЕ ЗАВЕРШЕНО!',
      totalChests: 'СУНДУКИ',
      bestRecord: 'РЕКОРД',
      scorecard: 'Статистика погружения:',
      emptyReport: 'Ни одного сундука не собрано.',
      correct: 'Верно',
      missed: 'Ошибок',
      depth: 'ГЛУБИНА',
    },
    wizard: {
      title: 'Магический Волшебник',
      description: 'Произноси слова правильно, чтобы твой волшебник метал огненные шары, ледяные стрелы и молнии во врагов! 🧙‍♂️✨',
      start: 'Начать колдовство',
      score: 'Побеждено монстров',
      best: 'Рекорд',
      paused: 'Пауза',
      resume: 'Продолжить',
      pause: 'Пауза',
      chooseSet: 'Выбрать набор слов',
      myWords: 'Мои слова',
      sayThis: '🎯 ПРОИЗНЕСИ ДЛЯ ЗАКЛИНАНИЯ!:',
      chooseTheme: 'ВЫБЕРИ СТИХИЮ ВОЛШЕБНИКА:',
      gameOverTitle: 'БИТВА МАГОВ ЗАВЕРШЕНА!',
      gameOverSubtitle: 'Магический портал закрылся. Твои результаты:',
      playAgain: 'Сыграть снова',
    },
    sentenceBird: {
      title: 'Фразоптичка',
      subtitle: 'Произнеси одно слово, чтобы лететь через трубы.',
      startLabel: 'Начать полёт',
      score: 'Очки',
      best: 'Рекорд',
      completed: 'Готово',
      chooseSet: 'Выбери набор слов',
      myWords: 'Мои слова',
      chooseTheme: 'Выбери тему неба',
      targetRibbon: 'Произнеси слово',
      ready: 'Готов слушать.',
      detected: 'Распознано',
      completedTitle: 'Ты справился, чемпион!',
      completedText: 'Ты пролетел через все слова в наборе.',
      failureTitle: 'Ой, разбился!',
      failureText: 'У тебя кончились жизни. Попробуй снова!',
      playAgain: 'Играть снова',
      back: 'Назад в хаб',
      world: 'Мир',
      emptySet: 'Добавь слова в Мои слова или выбери готовый набор.',
      wordsMastered: 'Слов освоено:',
      accuracy: 'Точность',
      speakLabel: 'Скажи!',
    },
    echo: {
      title: 'Эхо-микрофон',
      subtitle: 'Слушай и повторяй цепочку!',
      back: 'Назад в хаб',
      start: 'Начать уровень',
      chooseLevel: 'Выбери сложность',
      chooseTheme: 'Выбери тему эха',
      levelOne: 'Простые слова',
      levelTwo: 'Короткие фразы',
      levelThree: 'Идиомы',
      best: 'Рекорд',
      howToPlay: 'Как играть',
      learnRules: 'Правила',
      lobbyTitle: 'Эхо-микрофон',
      lobbyIntro: 'Внимательно слушай последовательность, а затем повторяй её в том же порядке!',
      lobbyStepOne: 'Слушай каждое слово в последовательности.',
      lobbyStepTwo: 'Повторяй слова по порядку.',
      lobbyStepThree: 'Удлиняй цепочку и проходи уровень!',
      listening: 'Фаза прослушивания: следи за произношением...',
      speaking: 'Говори сейчас: повторяй слова по порядку!',
      replay: 'Повторить подсказку',
      currentChain: 'Текущая цепочка',
      levelTarget: 'Цель уровня',
      bestChain: 'Лучшая цепочка',
      perfectMatch: 'Идеальное эхо!',
      perfectDesc: 'Порядок и произношение были безупречны. Приготовься к более длинной цепочке!',
      growChain: 'Удлинить цепочку',
      proceed: 'Перейти к уровню',
      restart: 'Начать заново',
      victory: 'ЭХО-МИКРОФОН ПРОЙДЕН!',
      victoryDesc: 'Невероятный результат! Ты прошёл все уровни голосовых цепочек.',
      replayAll: 'Пройти всё заново',
      tryAgain: 'Попробуй ещё раз!',
      missedAt: 'Ошибка на слове',
      startOver: 'Начнём последовательность заново!',
      phonetic: 'Фонетика',
      score: 'Очки',
      completed: 'Готово',
      chainWords: 'Слова',
      pts: 'очк',
      word: 'Слово',
      translation: 'Перевод',
      target: 'Цель',
      memoryCard: 'КАРТА ПАМЯТИ',
      sayNext: 'ГОВОРИ',
      idle: 'Приёмник ожидает',
      voiceActive: 'Микрофон активен',
      muted: 'Микрофон выключен',
      guide: 'Подсказка',
      words: 'слов',
      level: 'Уровень',
      speakLabel: 'Говори!',
      voiceFeed: 'Голосовой канал',
      pronRef: 'Справочник произношения',
      supremeMaster: 'Верховный мастер памяти!',
      finalScore: 'Финальный счёт',
      longestChainLabel: 'Самая длинная цепочка',
      totalAttemptsLabel: 'Всего попыток',
      correctRoundsLabel: 'Правильных раундов',
      lives: 'Жизни',
      gameOverBadge: 'Сердца закончились',
      gameOverTitle: 'ИГРА ОКОНЧЕНА',
      gameOverDesc: 'Ты ошибся три раза. Отличная тренировка памяти - попробуй ещё раз и побей свою цепочку!',
      playAgain: 'Играть снова',
      previewWord: 'Слово',
      themes: {
        studio: '🎧 Студия',
        forest: '🌲 Лес',
        space: '🪐 Космос',
      },
      levels: {
        1: { subtitle: 'Простые слова' },
        2: { subtitle: 'Короткие фразы' },
        3: { subtitle: 'Идиомы и скороговорки' },
      },
    },
    themes: {
      racer: {
        forest: '🌲 Лесная Трасса',
        night: '🌌 Космическая Ночь',
        desert: '🏜️ Золотая Пустыня',
        city: '🏎️ Неоновый Город',
      },
      ladder: {
        earth: '🌍 Орбита Земли',
        mars: '🔴 Полет на Марс',
        nebula: '🌌 Чужая Туманность',
      },
      bubble: {
        sky: '☁️ Плывущие облака',
        snow: '❄️ Снежная пустыня',
        starry: '🌙 Лунные искры',
        nebula: '🌌 Космические галактики',
      },
      boss: {
        castle: '🏰 Руины Замка',
        lava: '🌋 Лавовое Подземелье',
        forest: '🌲 Волшебный Лес',
        abyss: '🌌 Бездна Пустоты',
      },
      aste: {
        galaxy: '🌌 Галактика',
        supernova: '☀️ Сверхновая',
        aurora: '🌈 Аврора',
      },
      skate: {
        forest: '🌲 Лес',
        sunset: '🌇 Закат',
        neon: '🌃 Неон',
      },
      treasure: {
        yellow: '🟡 Жёлтая',
        orange: '🟠 Оранжевая',
        cyan: '🔵 Голубая',
        neon: '🟢 Неоновая',
      },
      wizard: {
        fire: '🔥 Огонь',
        ice: '❄️ Лёд',
        lightning: '⚡ Молния',
      },
      sentenceBird: {
        forest: '🌲 Лес',
        winter: '❄️ Зима',
        space: '🌌 Космос',
        ninja: '🥷 Ночь ниндзя',
      },
    },
    bubble: {
      gameSelected: 'Выбрана игра',
      title: 'Лопание пузырей',
      hubPortal: 'Портал хаба',
      chooseSkyAtmosphere: 'ВЫБЕРИ ТЕМУ НЕБА:',
      wordListTopic: 'ТЕМА СПИСКА СЛОВ:',
      listenAndPractice: 'СЛУШАЙ И ПРАКТИКУЙСЯ',
      customWordsBuilder: 'КОНСТРУКТОР СВОИХ СЛОВ',
      gameOverTitle: 'СУПЕР ЛОПАНИЕ ПУЗЫРЕЙ!',
      gameOverSubtitle: 'Пузырьковая гонка закончилась! Посмотри на результат ниже:',
      poppingScore: 'ОЧКИ ЗА ЛОПАНИЕ',
      personalHigh: 'ЛИЧНЫЙ РЕКОРД',
      scoreCard: 'Твоя таблица слов:',
      playAgain: 'Снова лопать!',
      bubbleOptions: 'Настройки пузырей',
      exitToPortal: 'ВЫЙТИ В ХАБ',
      wordsHeard: 'Услышанные слова:',
      sayAnyWord: 'Произнеси любое слово на пузырях!',
      words: 'СЛОВА:',
      quit: 'ВЫЙТИ',
      points: 'ОЧКИ:',
      clueLabel: 'Подсказки:',
      poppedLabel: 'Лопнуло:',
      listenInRussian: 'Слушать по-русски',
      hearWord: 'Услышь слово',
      voiceEngineLive: 'Голосовой движок запущен! Произноси английские слова, чтобы лопать пузыри!',
    },
  },
};

const UiLanguageContext = createContext<UiLanguageContextValue | undefined>(undefined);

export function UiLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<UiLanguage>(() => {
    if (typeof window === 'undefined') {
      return 'ru';
    }

    try {
      const saved = window.localStorage.getItem(STORAGE_KEY);
      return saved === 'en' ? 'en' : 'ru';
    } catch {
      return 'ru';
    }
  });

  useEffect(() => {
    if (typeof window === 'undefined') {
      return;
    }

    try {
      window.localStorage.setItem(STORAGE_KEY, language);
    } catch {
      // Ignore storage access errors in restricted environments.
    }
  }, [language]);

  const value = useMemo<UiLanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    t: (path: string) => {
      const keys = path.split('.');
      let current: unknown = UI_TEXT[language];

      for (const key of keys) {
        if (typeof current !== 'object' || current === null || !(key in current)) {
          return path;
        }
        current = (current as Record<string, unknown>)[key];
      }

      return typeof current === 'string' ? current : path;
    },
  }), [language]);

  return <UiLanguageContext.Provider value={value}>{children}</UiLanguageContext.Provider>;
}

export function useUiLanguage() {
  const context = useContext(UiLanguageContext);

  if (context) {
    return context;
  }

  return {
    language: 'ru' as UiLanguage,
    setLanguage: () => undefined,
    t: (path: string) => {
      const keys = path.split('.');
      let current: unknown = UI_TEXT.ru;

      for (const key of keys) {
        if (typeof current !== 'object' || current === null || !(key in current)) {
          return path;
        }
        current = (current as Record<string, unknown>)[key];
      }

      return typeof current === 'string' ? current : path;
    },
  };
}
